CREATE DATABASE APP_DEPLOYER_DB;
USE APP_DEPLOYER_DB;
CREATE TABLE USER_INPUT(
PROJECT_ID INTEGER NOT NULL auto_increment,
PROJECT_NAME VARCHAR(20) NOT NULL,
PROJECT_URL VARCHAR(40) NOT NULL,
CONSTRAINT PK_ADD_ZIP PRIMARY KEY(PROJECT_ID)
);